# Generated by nixos-generate-config on samsara; fileSystems/LUKS/swap live in disko.nix.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  # Force-load the USB HID path at initrd start instead of waiting for udev to
  # modprobe it on device match. udev otherwise registers usbhid ~2.4s in, which
  # is after a keyboard on a CPU-direct port has already enumerated — leaving it
  # unbound while the LUKS passphrase prompt is up.
  boot.initrd.kernelModules = [
    "xhci_pci"
    "usbhid"
    "hid_generic"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
